# Generated by Django 4.0.6 on 2022-07-13 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True)),
                ('death_date', models.DateTimeField(null=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.TextField(max_length=200)),
                ('birth_country', models.TextField(blank=True, max_length=200)),
                ('birth_region', models.TextField(blank=True, max_length=200)),
                ('history', models.TextField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(null=True, upload_to='profile_images/')),
                ('father', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
