# Generated by Django 4.0.6 on 2022-07-16 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='partner',
            field=models.ManyToManyField(related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='personallyregister',
            field=models.BooleanField(default=False),
        ),
    ]
