# Generated by Django 4.0.6 on 2022-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_partner_person_personallyregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partner',
        ),
        migrations.AlterField(
            model_name='person',
            name='personallyregister',
            field=models.BooleanField(default=True),
        ),
    ]
