# Generated by Django 4.0.6 on 2022-07-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='death_date',
        ),
    ]
