# Generated by Django 4.0.6 on 2022-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_person_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
