# Generated by Django 4.0.6 on 2022-07-13 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discussionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_theme', models.CharField(max_length=2000)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('id_user_create', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='videos_shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_video', models.FileField(upload_to='')),
                ('id_theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discussion.discussiontheme')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_message', models.TextField(max_length=220000)),
                ('date_message', models.DateTimeField(default=datetime.datetime.now)),
                ('id_theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discussion.discussiontheme')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='images_shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.FileField(upload_to='')),
                ('id_theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discussion.discussiontheme')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.person')),
            ],
        ),
    ]
