# Generated by Django 4.0.6 on 2022-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_remove_images_shared_id_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_shared',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videos_shared',
            old_name='id_user',
            new_name='user',
        ),
    ]
